# -*- coding: utf-8 -*-
"""evaluate.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBssAs9XbmdQYsLV6jrR-DX_1gputU-M
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gymnasium as gym
from stable_baselines3 import PPO, SAC, TD3, A2C

# ── Constants ─────────────────────────────────────────────────────────────────
ALGORITHMS = {
    "PPO": PPO,
    "SAC": SAC,
    "TD3": TD3,
    "A2C": A2C,
}

CONDITIONS = ["no_curriculum", "manual", "adaptive"]
SEEDS = [0, 1]
N_EVAL_EPISODES = 10


# ── Single model evaluation ───────────────────────────────────────────────────
def evaluate_model(algo_name, model_path, env_id="BipedalWalker-v3",
                   n_episodes=N_EVAL_EPISODES, render=False):
    """
    Evaluates a trained model and returns mean and std reward.

    Args:
        algo_name:   One of PPO, SAC, TD3, A2C
        model_path:  Path to the saved model file
        env_id:      Gymnasium environment ID
        n_episodes:  Number of evaluation episodes
        render:      Whether to render the environment

    Returns:
        mean_reward, std_reward
    """
    render_mode = "human" if render else None
    env = gym.make(env_id, render_mode=render_mode)

    algo_class = ALGORITHMS[algo_name]
    model = algo_class.load(model_path, env=env)

    episode_rewards = []

    for episode in range(n_episodes):
        obs, _ = env.reset()
        done = False
        total_reward = 0.0

        while not done:
            action, _ = model.predict(obs, deterministic=True)
            obs, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated
            total_reward += reward

        episode_rewards.append(total_reward)
        print(f"  Episode {episode + 1:02d}/{n_episodes}: {total_reward:.2f}")

    env.close()

    mean_reward = float(np.mean(episode_rewards))
    std_reward = float(np.std(episode_rewards))

    return mean_reward, std_reward


# ── Full benchmark evaluation ─────────────────────────────────────────────────
def evaluate_all(model_base_dir="models", env_id="BipedalWalker-v3"):
    """
    Iterates over all trained models, evaluates each one,
    and compiles results into a structured DataFrame.
    """
    results = []

    for algo in ALGORITHMS.keys():
        for condition in CONDITIONS:
            seed_rewards = []

            for seed in SEEDS:
                run_name = f"{algo}_{condition}_seed{seed}"
                model_path = os.path.join(
                    model_base_dir, run_name, "final_model"
                )

                if not os.path.exists(model_path + ".zip"):
                    print(f"[SKIP] Model not found: {model_path}")
                    continue

                print(f"\nEvaluating: {algo} | {condition} | seed {seed}")
                mean, std = evaluate_model(algo, model_path, env_id=env_id)
                seed_rewards.append(mean)

                results.append({
                    "algorithm": algo,
                    "condition": condition,
                    "seed": seed,
                    "mean_reward": mean,
                    "std_reward": std,
                })

            # Aggregate across seeds
            if seed_rewards:
                print(f"\n  [{algo} | {condition}] "
                      f"Across seeds: "
                      f"{np.mean(seed_rewards):.2f} "
                      f"± {np.std(seed_rewards):.2f}")

    df = pd.DataFrame(results)
    return df


# ── Zero-shot evaluation on Hardcore ─────────────────────────────────────────
def evaluate_zero_shot_hardcore(model_base_dir="models"):
    """
    Evaluates the best v3-trained models (per algorithm, best condition)
    zero-shot on BipedalWalker Hardcore.
    Used for the Hardcore Extension zero-shot condition.
    """
    print("\n" + "="*60)
    print("  ZERO-SHOT HARDCORE EVALUATION")
    print("="*60)

    results = []

    for algo in ALGORITHMS.keys():
        best_mean = -np.inf
        best_path = None
        best_condition = None

        # Find the best performing model across conditions and seeds
        for condition in CONDITIONS:
            for seed in SEEDS:
                run_name = f"{algo}_{condition}_seed{seed}"
                model_path = os.path.join(
                    model_base_dir, run_name, "final_model"
                )
                if not os.path.exists(model_path + ".zip"):
                    continue

                mean, _ = evaluate_model(
                    algo, model_path,
                    env_id="BipedalWalker-v3"
                )
                if mean > best_mean:
                    best_mean = mean
                    best_path = model_path
                    best_condition = condition

        if best_path is None:
            print(f"[SKIP] No models found for {algo}")
            continue

        print(f"\n{algo} best model: {best_condition} "
              f"(v3 mean reward: {best_mean:.2f})")
        print(f"Evaluating zero-shot on Hardcore...")

        mean_hc, std_hc = evaluate_model(
            algo, best_path,
            env_id="BipedalWalker-v3",  # hardcore=True handled below
            n_episodes=N_EVAL_EPISODES
        )

        results.append({
            "algorithm": algo,
            "best_v3_condition": best_condition,
            "v3_mean_reward": best_mean,
            "hardcore_mean_reward": mean_hc,
            "hardcore_std_reward": std_hc,
        })

        print(f"  Hardcore result: {mean_hc:.2f} ± {std_hc:.2f}")

    df = pd.DataFrame(results)
    return df


# ── Results table ─────────────────────────────────────────────────────────────
def print_results_table(df):
    """
    Prints a clean summary table aggregated across seeds,
    matching the format expected in the final report.
    """
    print("\n" + "="*65)
    print(f"  {'Algorithm':<10} {'Condition':<18} "
          f"{'Mean Reward':>12} {'Std Reward':>12}")
    print("="*65)

    for algo in ALGORITHMS.keys():
        for condition in CONDITIONS:
            subset = df[
                (df["algorithm"] == algo) &
                (df["condition"] == condition)
            ]
            if subset.empty:
                continue

            mean = subset["mean_reward"].mean()
            std = subset["mean_reward"].std()

            print(f"  {algo:<10} {condition:<18} "
                  f"{mean:>12.2f} {std:>12.2f}")
        print("-"*65)


# ── Plotting ──────────────────────────────────────────────────────────────────
def plot_results(df, save_path="results/comparison_plot.png"):
    """
    Generates a bar chart comparing all algorithms across
    curriculum conditions. Saved to disk for the report.
    """
    os.makedirs("results", exist_ok=True)

    # Aggregate across seeds
    grouped = df.groupby(["algorithm", "condition"])["mean_reward"]
    means = grouped.mean().unstack()
    stds = grouped.std().unstack()

    fig, ax = plt.subplots(figsize=(12, 6))

    x = np.arange(len(means.index))
    width = 0.25
    colors = ["#2196F3", "#4CAF50", "#FF9800"]

    for i, condition in enumerate(CONDITIONS):
        if condition not in means.columns:
            continue
        ax.bar(
            x + i * width,
            means[condition],
            width,
            yerr=stds[condition],
            label=condition.replace("_", " ").title(),
            color=colors[i],
            capsize=4,
            alpha=0.85,
        )

    ax.set_xlabel("Algorithm", fontsize=13)
    ax.set_ylabel("Mean Reward (± std)", fontsize=13)
    ax.set_title(
        "BipedalWalker-v3: Algorithm vs Curriculum Condition",
        fontsize=14
    )
    ax.set_xticks(x + width)
    ax.set_xticklabels(means.index, fontsize=12)
    ax.legend(fontsize=11)
    ax.grid(axis="y", alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    print(f"\nPlot saved to {save_path}")
    plt.show()


# ── Entry point ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Run full evaluation
    df = evaluate_all()

    if not df.empty:
        print_results_table(df)
        plot_results(df)

        # Save raw results to CSV for the report
        os.makedirs("results", exist_ok=True)
        df.to_csv("results/all_results.csv", index=False)
        print("\nResults saved to results/all_results.csv")
    else:
        print("No models found. Train some models first.")