# -*- coding: utf-8 -*-
"""simplified_terrain.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MWcjaVbTL5ak3FGBMDtpsmP9cq5IAfL
"""

import gymnasium as gym
import numpy as np
from gymnasium import Wrapper
from gymnasium.envs.box2d.bipedal_walker import BipedalWalker, TERRAIN_HEIGHT, TERRAIN_STEP, TERRAIN_LENGTH, TERRAIN_GRASS


class SimplifiedTerrainWrapper(Wrapper):
    """
    A custom Gymnasium wrapper for BipedalWalker-v3 that creates a
    simplified terrain for curriculum learning.

    roughness=0.0 → completely flat terrain (easiest)
    roughness=1.0 → standard BipedalWalker-v3 terrain (full difficulty)
    """

    def __init__(self, env, roughness=0.3):
        super().__init__(env)
        assert 0.0 <= roughness <= 1.0, "Roughness must be between 0.0 and 1.0"
        self.roughness = roughness

    def reset(self, **kwargs):
        # 1. Reset environment normally
        obs, info = self.env.reset(**kwargs)

        # 2. Modify terrain AFTER reset
        self._override_terrain()

        # 3. DO NOT call reset or step again
        # Observation is still valid in most cases
        return obs, info

    def _override_terrain(self):
        """
        Regenerates the terrain with reduced roughness by directly
        modifying the Box2D world after the standard reset.
        """
        unwrapped = self.env.unwrapped

        # Destroy existing terrain bodies
        for t in unwrapped.terrain:
            unwrapped.world.DestroyBody(t)
        unwrapped.terrain = []

        # Regenerate terrain with scaled roughness
        # BipedalWalker terrain is built from height samples
        # We scale the variation around the base TERRAIN_HEIGHT
        terrain_length = TERRAIN_LENGTH
        height = TERRAIN_HEIGHT

        # Generate height samples with scaled roughness
        heights = []
        current_height = height
        for i in range(terrain_length):
            if i < TERRAIN_GRASS:
                # Keep the starting grass area flat always
                heights.append(height)
            else:
                # Scale the random variation by roughness
                variation = np.random.uniform(-1.0, 1.0) * self.roughness * 0.5
                current_height = height + variation
                # Clamp to reasonable range
                current_height = np.clip(current_height, height - 1.0, height + 1.0)
                heights.append(current_height)

        # Rebuild terrain polygons in the Box2D world
        self._rebuild_terrain_bodies(unwrapped, heights)

    def _rebuild_terrain_bodies(self, unwrapped, heights):
        """
        Rebuilds the Box2D static terrain bodies from the height array.
        """
        from Box2D.b2 import staticBody, polygonShape

        for i in range(len(heights) - 1):
            x1 = i * TERRAIN_STEP
            x2 = (i + 1) * TERRAIN_STEP
            y1 = heights[i]
            y2 = heights[i + 1]

            body = unwrapped.world.CreateStaticBody(
                shapes=polygonShape(vertices=[
                    (x1, 0),
                    (x1, y1),
                    (x2, y2),
                    (x2, 0)
                ])
            )
            body.color1 = (0.0, 0.0, 0.0)
            body.color2 = (0.0, 0.0, 0.0)
            unwrapped.terrain.append(body)

    def step(self, action):
        return self.env.step(action)


class AdaptiveTerrainWrapper(SimplifiedTerrainWrapper):
    """
    Extends SimplifiedTerrainWrapper with adaptive difficulty.
    Automatically increases roughness when the agent reaches
    mean_reward >= threshold over window_size episodes.

    Used for Condition C (Adaptive Curriculum).
    """

    def __init__(self, env, initial_roughness=0.2, target_roughness=1.0,
                 roughness_step=0.1, reward_threshold=100.0, window_size=10):
        super().__init__(env, roughness=initial_roughness)
        self.initial_roughness = initial_roughness
        self.target_roughness = target_roughness
        self.roughness_step = roughness_step
        self.reward_threshold = reward_threshold
        self.window_size = window_size

        self.episode_rewards = []
        self.current_episode_reward = 0.0
        self.transferred = False

    def step(self, action):
        obs, reward, terminated, truncated, info = self.env.step(action)
        self.current_episode_reward += reward

        if terminated or truncated:
            self.episode_rewards.append(self.current_episode_reward)
            self.current_episode_reward = 0.0

            # Check transfer condition over last window_size episodes
            if len(self.episode_rewards) >= self.window_size:
                recent_mean = np.mean(self.episode_rewards[-self.window_size:])

                if recent_mean >= self.reward_threshold and not self.transferred:
                    # Increase roughness
                    new_roughness = min(
                        self.roughness + self.roughness_step,
                        self.target_roughness
                    )
                    if new_roughness != self.roughness:
                        self.roughness = new_roughness
                        print(f"[AdaptiveWrapper] Roughness increased to "
                              f"{self.roughness:.2f} "
                              f"(mean reward: {recent_mean:.2f})")

                    if self.roughness >= self.target_roughness:
                        self.transferred = True
                        print(f"[AdaptiveWrapper] Full difficulty reached.")

        return obs, reward, terminated, truncated, info

    def reset(self, **kwargs):
        return super().reset(**kwargs)

    @property
    def is_fully_transferred(self):
        return self.transferred


def make_env_no_curriculum(seed=0):
    """Condition A: Standard BipedalWalker-v3, no curriculum."""
    env = gym.make("BipedalWalker-v3")
    env.reset(seed=seed)
    return env


def make_env_manual_curriculum(seed=0, roughness=0.2):
    """Condition B: Simplified terrain, fixed 300K steps then transfer."""
    base_env = gym.make("BipedalWalker-v3")
    env = SimplifiedTerrainWrapper(base_env, roughness=roughness)
    env.reset(seed=seed)
    return env


def make_env_adaptive_curriculum(seed=0):
    """Condition C: Adaptive terrain, transfers when mean reward >= 100."""
    base_env = gym.make("BipedalWalker-v3")
    env = AdaptiveTerrainWrapper(
        base_env,
        initial_roughness=0.2,
        target_roughness=1.0,
        roughness_step=0.1,
        reward_threshold=100.0,
        window_size=10
    )
    env.reset(seed=seed)
    return env


# ── Quick test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Testing No Curriculum environment...")
    env_a = make_env_no_curriculum(seed=0)
    obs, _ = env_a.reset()
    print(f"  Obs shape: {obs.shape}")  # Should be (24,)
    env_a.close()

    print("\nTesting Manual Curriculum environment...")
    env_b = make_env_manual_curriculum(seed=0, roughness=0.2)
    obs, _ = env_b.reset()
    print(f"  Obs shape: {obs.shape}")
    env_b.close()

    print("\nTesting Adaptive Curriculum environment...")
    env_c = make_env_adaptive_curriculum(seed=0)
    obs, _ = env_c.reset()
    print(f"  Obs shape: {obs.shape}")
    env_c.close()

    print("\nAll environment tests passed.")