# -*- coding: utf-8 -*-
"""train.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HU9UFYfV3x8O69Ce_wfo9fyZUNmSKveI
"""

import os
import numpy as np
import gymnasium as gym
from stable_baselines3 import PPO, SAC, TD3, A2C
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.callbacks import (
    EvalCallback,
    CheckpointCallback,
    BaseCallback
)
from simplified_terrain import (
    make_env_no_curriculum,
    make_env_manual_curriculum,
    make_env_adaptive_curriculum,
    SimplifiedTerrainWrapper
)

# ── Constants ─────────────────────────────────────────────────────────────────
TOTAL_TIMESTEPS = 1_000_000
MANUAL_TRANSFER_TIMESTEPS = 300_000
EVAL_FREQ = 10_000
EVAL_EPISODES = 10
CHECKPOINT_FREQ = 100_000

ALGORITHMS = {
    "PPO": PPO,
    "SAC": SAC,
    "TD3": TD3,
    "A2C": A2C,
}


# ── Custom callback for manual curriculum transfer ────────────────────────────
class ManualCurriculumCallback(BaseCallback):
    """
    At MANUAL_TRANSFER_TIMESTEPS, replaces the simplified terrain
    environment with standard BipedalWalker-v3 (full difficulty).
    Used for Condition B.
    """

    def __init__(self, transfer_at=MANUAL_TRANSFER_TIMESTEPS, verbose=1):
        super().__init__(verbose)
        self.transfer_at = transfer_at
        self.transferred = False

    def _on_step(self) -> bool:
        if not self.transferred and self.num_timesteps >= self.transfer_at:
            if self.verbose:
                print(f"\n[ManualCurriculum] Transferring to standard v3 "
                      f"at timestep {self.num_timesteps}")
            # Replace the environment with standard v3
            new_env = DummyVecEnv([
                lambda: Monitor(gym.make("BipedalWalker-v3"))
            ])
            self.model.set_env(new_env)
            self.transferred = True
        return True


# ── Environment factory ───────────────────────────────────────────────────────
def make_monitored_env(condition, seed, log_dir):
    """
    Creates and returns a monitored, vectorized environment
    based on the curriculum condition.
    """
    os.makedirs(log_dir, exist_ok=True)

    if condition == "no_curriculum":
        env = make_env_no_curriculum(seed=seed)

    elif condition == "manual":
        env = make_env_manual_curriculum(seed=seed, roughness=0.2)

    elif condition == "adaptive":
        env = make_env_adaptive_curriculum(seed=seed)

    elif condition == "hardcore":
        env = gym.make("BipedalWalker-v3", hardcore=True)
        env.reset(seed=seed)

    else:
        raise ValueError(f"Unknown condition: {condition}")

    env = Monitor(env, log_dir)
    env = DummyVecEnv([lambda: env])
    return env


# ── Main training function ────────────────────────────────────────────────────
def train(algo_name, condition, seed, timesteps=TOTAL_TIMESTEPS):
    """
    Trains a single algorithm under a single curriculum condition
    with a single seed.

    Args:
        algo_name:  One of PPO, SAC, TD3, A2C
        condition:  One of no_curriculum, manual, adaptive, hardcore
        seed:       Integer seed for reproducibility
        timesteps:  Total training timesteps
    """
    print(f"\n{'='*60}")
    print(f"  Algorithm : {algo_name}")
    print(f"  Condition : {condition}")
    print(f"  Seed      : {seed}")
    print(f"  Timesteps : {timesteps:,}")
    print(f"{'='*60}\n")

    # Directories
    run_name = f"{algo_name}_{condition}_seed{seed}"
    log_dir = f"logs/{run_name}"
    model_dir = f"models/{run_name}"
    eval_log_dir = f"eval_logs/{run_name}"
    os.makedirs(model_dir, exist_ok=True)
    os.makedirs(eval_log_dir, exist_ok=True)

    # Training environment
    train_env = make_monitored_env(condition, seed, log_dir)

    # Evaluation environment — always standard v3 for fair comparison
    eval_env = DummyVecEnv([
        lambda: Monitor(gym.make("BipedalWalker-v3"))
    ])

    # Algorithm hyperparameters
    # Using SB3 defaults — kept identical across all algorithms
    # to isolate curriculum as the only variable
    algo_class = ALGORITHMS[algo_name]

    model = algo_class(
        policy="MlpPolicy",
        env=train_env,
        verbose=1,
        tensorboard_log=log_dir,
        seed=seed,
    )

    # Callbacks
    callbacks = []

    # Evaluation callback — evaluates on standard v3 every EVAL_FREQ steps
    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=f"{model_dir}/best",
        log_path=eval_log_dir,
        eval_freq=EVAL_FREQ,
        n_eval_episodes=EVAL_EPISODES,
        deterministic=True,
        render=False,
        verbose=1,
    )
    callbacks.append(eval_callback)

    # Checkpoint callback — saves model every CHECKPOINT_FREQ steps
    checkpoint_callback = CheckpointCallback(
        save_freq=CHECKPOINT_FREQ,
        save_path=f"{model_dir}/checkpoints",
        name_prefix=run_name,
        verbose=1,
    )
    callbacks.append(checkpoint_callback)

    # Manual curriculum callback — only for Condition B
    if condition == "manual":
        manual_callback = ManualCurriculumCallback(
            transfer_at=MANUAL_TRANSFER_TIMESTEPS,
            verbose=1,
        )
        callbacks.append(manual_callback)

    # Train
    model.learn(
        total_timesteps=timesteps,
        callback=callbacks,
        tb_log_name=run_name,
        progress_bar=True,
    )

    # Save final model
    final_path = f"{model_dir}/final_model"
    model.save(final_path)
    print(f"\nModel saved to {final_path}")

    train_env.close()
    eval_env.close()

    return final_path


# ── Quick test ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Quick smoke test — 10K steps just to verify no errors
    train(
        algo_name="PPO",
        condition="no_curriculum",
        seed=0,
        timesteps=10_000
    )